
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ak859784
 */
public class BatailleDlg extends java.awt.Dialog {
    

    /**
     * Creates new form BatailleDlg
     */
    private LesJoueurs lj;       //collection des joueurs (en entrée)
    private int indj;            //indice du joueur courant (en entrée)
    private Joueur adversaire;   //adversaire sélectionné (en sortie)
    private boolean ok;          // action faite ou non (en sortie)
    private Bataille b;          // action réalisée
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Vainqueur = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        Demarrer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Joueur = new javax.swing.JLabel();
        Adversaire = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfosCarte1 = new javax.swing.JTextArea();
        Carte1 = new javax.swing.JButton();
        Carte2 = new javax.swing.JButton();
        Ic2 = new javax.swing.JScrollPane();
        InfosCarte2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        MessageJ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListJ = new javax.swing.JList<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        Vainqueur.setText("jLabel1");
        jPanel1.add(Vainqueur);

        Annuler.setText("Annuler/Fermer");
        jPanel1.add(Annuler);

        Demarrer.setText("Démarrer");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });
        jPanel1.add(Demarrer);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));
        jPanel4.add(Joueur);
        jPanel4.add(Adversaire);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        InfosCarte1.setColumns(20);
        InfosCarte1.setRows(5);
        jScrollPane1.setViewportView(InfosCarte1);

        jPanel5.add(jScrollPane1);
        jPanel5.add(Carte1);
        jPanel5.add(Carte2);

        InfosCarte2.setColumns(20);
        InfosCarte2.setRows(5);
        Ic2.setViewportView(InfosCarte2);

        jPanel5.add(Ic2);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        MessageJ.setToolTipText("");
        jPanel3.add(MessageJ);

        ListJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListJMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListJ);

        jPanel3.add(jScrollPane2);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void ListJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListJMouseClicked
        // TODO add your handling code here:
        int ind = ListJ.getSelectedIndex();  // Récuperation de l'indice du joueur séléctionné
        if(ind!=-1){  
            Joueur jo = this.lj.getJoueur(indj);  // Récuperation du joueur courant
            if(this.lj.getJoueur(ind).getPseudo().equals(jo.getPseudo())) // Si le pseudo du joueur séléctionné est celui du joueur courant
                Joueur.setText("Selectionner un joueur different"); // Affichage d'un message
            else { // si non 
                this.adversaire = lj.getJoueur(ind); // Récuperation du joueur séléctionné
                b = new Bataille(jo, this.adversaire); // Création d'un objet de type Bataille en appelant le constructeur de la classe Bataille qui prend en paramètres j courant, j séléctionné(adversaire).
                Annuler.setVisible(true); // Rendre le bouton annuler visisble
                Joueur.setText(""+jo.getPseudo()); // Affichege du pseudo du joueur 
                Adversaire.setText(this.adversaire.getPseudo()); // Affichege du pseudo d'adversaire
                InfosCarte1.setText(jo.getPaquet().toString());  // Affichage du paquet du joueur 
                InfosCarte2.setText(this.adversaire.getPaquet().toString()); // Affichage du paquet d'adversaire 
            }
        }
    }//GEN-LAST:event_ListJMouseClicked

    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
        // TODO add your handling code here:
        Joueur jc = lj.getJoueur(indj);  // Récuperation du joueur courant
        InfosCarte1.append("\n"+jc.getPseudo()+" joueur "+jc.getPaquet().getPerso(0)); // Ajout d'un texte a la zone d'édition (InfosCarte1)
        InfosCarte2.append("\n"+this.adversaire.getPseudo()+" joueur "+this.adversaire.getPaquet().getPerso(0)+"\n"); // Ajout d'un texte a la zone d'édition (InfosCarte2)
        int res = b.execute(); // récuperation de l'entier renvoyer par la methode execute de la classe bataille
        switch(res){ // Les instruction a effectuer selon la valeur de la variable res
            case 0 : InfosCarte1.append("ex-aequo aucun gagnant \n");
                     InfosCarte2.append("ex-aequo aucun gagnant \n");
                     break;
            case 1 : InfosCarte1.append(jc.getPseudo()+" gagne \n ");
                     InfosCarte2.append(this.adversaire.getPseudo()+" perdu \n ");
                     Vainqueur.setText(jc.getPseudo());
                     break;
            case 2 : InfosCarte1.append(jc.getPseudo()+" perdu \n ");
                     InfosCarte2.append(this.adversaire.getPseudo()+" gagne \n ");
                     Vainqueur.setText(this.adversaire.getPseudo());
                     break;         
        }
        InfosCarte1.append(jc.getPaquet().toString());
        InfosCarte2.append(this.adversaire.getPaquet().toString());
        ok = true; // Affecter true a l'attribut ok
        LesPersonnages pjc = jc.getPaquet(); // Recuperation du paquet du joueur courant
        LesPersonnages pad = this.adversaire.getPaquet(); // Recuperation du paquet d'adversaire
        if(pjc.getTaille()==0 || pad.getTaille()==0){  // Si au moin la taille d'un des deux paquet est nul
            Demarrer.setEnabled(false); // Désactiver le bouton Demarrer
            Annuler.setText("Fermer"); // Changer le text du bouton Annuler a Fermer
        }
        else { // si non 
            pjc.getPerso(0).setImgBouton(Carte1); // Affichage de la première carte du paquet du joueur courant dans le bouton Carte1
            pad.getPerso(0).setImgBouton(Carte2); // Affichage de la première carte du paquet d'adversaire dans le bouton Carte2
        } 
    }//GEN-LAST:event_DemarrerActionPerformed
    public boolean isOk() { 
        return ok;
    }    
    public Joueur getAdversaire(){        
        return adversaire;
    }    
    public Bataille getBataille(){ 
        return b;
    }
    public BatailleDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj, int jc) {
        super(parent, modal); 
        initComponents();
        this.lj = lj;
        this.indj = jc;
        this.ok=false;
        this.b=null;
        initListJ();
        Annuler.setText("Annuler");
        Annuler.setVisible(false); // aucune bataille existe 
        MessageJ.setText(lj.getJoueur(indj).getPseudo()+" va effectuer une bataille contre : ");
    }
    /**
     * @param args the command line arguments
     */
    public void initListJ() {
        DefaultListModel mod = new DefaultListModel(); 
        ListJ.setModel(mod);
        for(int i=0;i<lj.getNbJoueurs();i++){
            mod.addElement(lj.getJoueur(i).getPseudo());
            ListJ.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        }
    }
    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {
        this.ok=false; // Affecter false a l'attribut ok
        if (Annuler.getText().equals("Annuler"))
            this.b.setDeroulement("Bataille interrompue en cours de partie");
        this.setVisible(false);
        this.dispose();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adversaire;
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Carte1;
    private javax.swing.JButton Carte2;
    private javax.swing.JButton Demarrer;
    private javax.swing.JScrollPane Ic2;
    private javax.swing.JTextArea InfosCarte1;
    private javax.swing.JTextArea InfosCarte2;
    private javax.swing.JLabel Joueur;
    private javax.swing.JList<String> ListJ;
    private javax.swing.JLabel MessageJ;
    private javax.swing.JLabel Vainqueur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
