
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rharm
 */
public class GestionPersonnages extends javax.swing.JFrame {
    private LesPersonnages lesPersos;

    /**
     * Creates new form GestionPersonnages
     */
    public GestionPersonnages() {
        initComponents();
        lesPersos = new LesPersonnages(10);
        initListeFamilles();
        Edition.setText("");
        
        
    }
    
    private void initListeFamilles(){
        ArrayList<String> lst;
        lst = lesPersos.getFamilles();
        for(int i=0;i<lst.size();i++)
            ListeFamilles.addItem(lst.get(i));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bAfficher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        bChercher = new javax.swing.JButton();
        ListeFamilles = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        BPhoto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AjoutPersoDlg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des Personnages");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel4.setLayout(new java.awt.GridLayout(5, 0));

        bAfficher.setText("Afficher");
        bAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfficherActionPerformed(evt);
            }
        });
        jPanel4.add(bAfficher);

        jLabel2.setText("Numéro cherché?");
        jPanel4.add(jLabel2);
        jPanel4.add(Numero);

        bChercher.setText("Chercher");
        bChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChercherActionPerformed(evt);
            }
        });
        jPanel4.add(bChercher);

        ListeFamilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeFamillesActionPerformed(evt);
            }
        });
        jPanel4.add(ListeFamilles);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout());
        jPanel5.add(BPhoto);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new java.awt.GridLayout());

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Gestion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AjoutPersoDlg.setText("Ajout");
        AjoutPersoDlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutPersoDlgActionPerformed(evt);
            }
        });
        jMenu1.add(AjoutPersoDlg);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfficherActionPerformed
        // TODO add your handling code here:
        Edition.setText(lesPersos.toString());
    }//GEN-LAST:event_bAfficherActionPerformed

    private void bChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChercherActionPerformed
        // TODO add your handling code here:
        
        String val = Numero.getText();
        if(!equals("")){
            int num = Integer.parseInt(val);
            if(0<=num && num<lesPersos.getTaille()){
                Personnage p = lesPersos.getPerso(num);
                Edition.setText(p.toString());
                //p.setImgBouton(BPhoto);
            }
            else Edition.setText("erreur num n'existe pas");
        }
    }//GEN-LAST:event_bChercherActionPerformed

    private void ListeFamillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeFamillesActionPerformed
        // TODO add your handling code here:
        int ind = ListeFamilles.getSelectedIndex();
        if(ind!=-1){
            String f = ListeFamilles.getSelectedItem().toString();
            LesPersonnages lp = lesPersos.getPersosFamille(f);
            Edition.setText(""+lp);
            
        }
            
        
        
    }//GEN-LAST:event_ListeFamillesActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    
    
    private void AjoutPersoDlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutPersoDlgActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AjoutPersoDlgActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPersonnages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutPersoDlg;
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JComboBox<String> ListeFamilles;
    private javax.swing.JTextField Numero;
    private javax.swing.JButton bAfficher;
    private javax.swing.JButton bChercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
