
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ak859784
 */
public class InitDlg extends java.awt.Dialog {

    /**
     * Creates new form InitDlg
     */
    private LesJoueurs lj; // les joueurs sélectionnés
    private boolean ok; // indicateur de fermeture
    private int nc; // niveau du jeu (4,10,18,32)

    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);  // appel au constructeur de la classe ancètre
        initComponents();  // appel a la methode initComponents qui contruit l'intérface qui a était faite
        lj = new LesJoueurs();  // initialiser l'attribut lj
        ok = false;  // initialiser l'attribut ok par false
        nc = 0; // initialiser l'attribut nc 
        Lara.setSelected(true);  // la case a cocher LARA est selectionnée par défaut 
        Jack.setSelected(true);  // la case a cocher JACK est selectionnée par défaut 
        Joueur j=new Joueur("Jack", "rares"); // Création d'un nouveau joueur Jack de la familles des rares
        j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png"))); // initialisation de la photo de jack 
        Image img = j.getImage().getImage().getScaledInstance(BPhoto.getWidth(),BPhoto.getHeight(),Image.SCALE_SMOOTH);//redimensionner la photo de jack afin de la stocker dans une variable img de type Image(passage par adresse)
        BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img  
        Edition.setText(""+j); // affichage des informations de jack dans la zone d'édition ( toString )
        Joueur l=new Joueur("Lara", "epiques"); // Création d'un nouveau joueur Jack de la familles des rares
        l.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg"))); // initialisation de la photo de jack 
        Image imgl = l.getImage().getImage().getScaledInstance(BPhoto.getWidth(),BPhoto.getHeight(),Image.SCALE_SMOOTH);//redimensionner la photo de lara afin de la stocker dans une variable img de type Image(passage par adresse)
        this.lj.ajouteJoueur(j); // ajout du joueur j aux joueurs sélectionnés
        this.lj.ajouteJoueur(l); // ajout du joueur l aux joueurs sélectionnés
    }
    public LesJoueurs getJoueurs() { return this.lj;}  // accesseur de lecture de l'attribut lj
    public boolean getOk() { return this.ok;} // accesseur de lecture de l'attribut ok
    public int getNiveau() {return this.nc;} // accesseur de lecture de l'attribut nc

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enfant = new javax.swing.JRadioButton();
        debutant = new javax.swing.JRadioButton();
        avance = new javax.swing.JRadioButton();
        expert = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lara = new javax.swing.JCheckBox();
        Jack = new javax.swing.JCheckBox();
        JeanSebastien = new javax.swing.JCheckBox();
        Amadeus = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez la taille du jeu");
        jPanel3.add(jLabel1);

        buttonGroup1.add(enfant);
        enfant.setText("enfant( 4 personnages, 2 familles)");
        enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfantActionPerformed(evt);
            }
        });
        jPanel3.add(enfant);

        buttonGroup1.add(debutant);
        debutant.setText("Débutant ( 10 personnages, 2 familles)");
        debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debutantActionPerformed(evt);
            }
        });
        jPanel3.add(debutant);

        buttonGroup1.add(avance);
        avance.setText("Avancé ( 18  personnages, 4 familles)");
        avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanceActionPerformed(evt);
            }
        });
        jPanel3.add(avance);

        buttonGroup1.add(expert);
        expert.setText("Expert ( 32 personnages, 6 familles)");
        expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertActionPerformed(evt);
            }
        });
        jPanel3.add(expert);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choisissez les joueurs crées par défauts");
        jPanel4.add(jLabel2);

        Lara.setText("Lara");
        Lara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaraActionPerformed(evt);
            }
        });
        jPanel4.add(Lara);

        Jack.setText("Jack");
        Jack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JackActionPerformed(evt);
            }
        });
        jPanel4.add(Jack);

        JeanSebastien.setText("Jean-Sébastien");
        JeanSebastien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JeanSebastienActionPerformed(evt);
            }
        });
        jPanel4.add(JeanSebastien);

        Amadeus.setText("Amadeus");
        Amadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmadeusActionPerformed(evt);
            }
        });
        jPanel4.add(Amadeus);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel5.add(jScrollPane1);
        jPanel5.add(BPhoto);

        jPanel1.add(jPanel5);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel2.add(Valider);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false); // rend la boite de dialogue invisible 
        dispose();  // récuperer l'espace mémoire
    }//GEN-LAST:event_closeDialog

    private void enfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfantActionPerformed
        // TODO add your handling code here:
        this.nc = 4; // affecter 4 à nc
    }//GEN-LAST:event_enfantActionPerformed

    private void debutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debutantActionPerformed
        // TODO add your handling code here:
        this.nc = 10; // affecter 10 à nc
    }//GEN-LAST:event_debutantActionPerformed

    private void avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanceActionPerformed
        // TODO add your handling code here:
        this.nc = 18; // affecter 18 à nc
    }//GEN-LAST:event_avanceActionPerformed

    private void expertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertActionPerformed
        // TODO add your handling code here:
        this.nc = 32; // affecter 32 à nc
    }//GEN-LAST:event_expertActionPerformed

    private void LaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaraActionPerformed
        // TODO add your handling code here:
        Joueur j = new Joueur("Lara","épiques");   // Création d'un nouveau joueur Lara de la familles des épiques
        j.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg"))); // initialisation de la photo de Lara 


        if(Lara.isSelected()){
        this.lj.ajouteJoueur(j);
        Edition.setText(""+j); // affichage des informations de jack dans la zone d'édition ( toString )
        Image img = j.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
        BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img  

        }
        else if(!Lara.isSelected()){
            this.lj.supprimeJoueur(j);
            if(this.lj.getNbJoueurs()!=0){
                Joueur dernier = this.lj.getJoueur(this.lj.getNbJoueurs()-1);
            Edition.setText(""+dernier); // vider la zone d'édition 
            Image img = dernier.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img  
            }
            else{
                Edition.setText("");
                BPhoto.setIcon(null);
            }
                
            
        }
        
                
    }//GEN-LAST:event_LaraActionPerformed

    private void JackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JackActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Jack", "rares");    // Création d'un nouveau joueur Lara de la familles des épiques
        j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png"))); // initialisation de la photo du joueur
        if(Jack.isSelected()){
            this.lj.ajouteJoueur(j);
            Image img = j.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img  

            Edition.setText(""+j); // affichage des informations du joueur dans la zone d'édition ( toString )
        }
        else if(!Jack.isSelected()){
            this.lj.supprimeJoueur(j);
            if(this.lj.getNbJoueurs()!=0){
                Joueur dernier = this.lj.getJoueur(this.lj.getNbJoueurs()-1);
            Edition.setText(""+dernier); // vider la zone d'édition 
            Image img = dernier.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img  
            }
            else{
                Edition.setText("");
                BPhoto.setIcon(null);
            }
            
        }
        
    }//GEN-LAST:event_JackActionPerformed

    private void JeanSebastienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JeanSebastienActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Jean-Sébastien", "famille j-s");  // Création d'un nouveau joueur Lara de la familles des épiques
        j.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg"))); // initialisation de la photo du joueur
        if(JeanSebastien.isSelected()){
        this.lj.ajouteJoueur(j);    
        Image img = j.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de Sebastien afin de la stocker dans une variable img de type Image (passage par adresse)
        BPhoto.setIcon(new ImageIcon(img));  // Modifier l'icon du Button(BPhoto) par img  
        Edition.setText(""+j);  // affichage des informations du joueur dans la zone d'édition ( toString )
        }
        
        else if(!JeanSebastien.isSelected()){
            this.lj.supprimeJoueur(j);
            if(this.lj.getNbJoueurs()!=0){
                Joueur dernier = this.lj.getJoueur(this.lj.getNbJoueurs()-1);
            Edition.setText(""+dernier); // vider la zone d'édition 
            Image img = dernier.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img 
            }
            
            else{
                Edition.setText("");
                BPhoto.setIcon(null);
            }
        }
    }//GEN-LAST:event_JeanSebastienActionPerformed

    private void AmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmadeusActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Amadeus", "famille amad");   // Création d'un nouveau joueur Amdeus  de la familles des famille amad 
        j.setPhoto(new ImageIcon(getClass().getResource("/img/joueurDefaut.png"))); // initialisation de la photo du joueur
        if(Amadeus.isSelected()){
            this.lj.ajouteJoueur(j);   
            Image img = j.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo d'Amadeus afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); 
            Edition.setText(""+j);  // affichage des informations du joueur dans la zone d'édition ( toString )
        }
        
        else if(!Amadeus.isSelected()){
           this.lj.supprimeJoueur(j);
           if(this.lj.getNbJoueurs()!=0){
               Joueur dernier = this.lj.getJoueur(this.lj.getNbJoueurs()-1);
            Edition.setText(""+dernier); // vider la zone d'édition 
            Image img = dernier.getImage().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH); // redimensionner la photo de lara afin de la stocker dans une variable img de type Image (passage par adresse)
            BPhoto.setIcon(new ImageIcon(img)); // Modifier l'icon du Button(BPhoto) par img 
           }
            
            else{
                Edition.setText("");
                BPhoto.setIcon(null);
            }
        }
    }//GEN-LAST:event_AmadeusActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        if((enfant.isSelected() || debutant.isSelected() || expert.isSelected() || avance.isSelected() )&& (lj.getNbJoueurs()>1)){
            /*if(Lara.isSelected()){
            Joueur jl=new Joueur("Lara", "épiques");  // Création d'un nouveau joueur Lara de la familles des épiques
            jl.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg"))); // initialisation de la photo du joueur
            lj.ajouteJoueur(jl); // ajout du joueur a la liste des joueurs selectionnées
        } 
        if(Jack.isSelected()){
            Joueur jj=new Joueur("Jack", "rares"); // Création d'un nouveau joueur Jack de la familles des rares 
            jj.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png"))); // initialisation de la photo du joueur
            lj.ajouteJoueur(jj); // ajout du joueur a la liste des joueurs selectionnées
        }
        if(JeanSebastien.isSelected()){
            Joueur js=new Joueur("Jean-Sébastien", "alpins-femmes"); // Création d'un nouveau joueur J-S de la familles des alpins-femmes
            js.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg"))); // initialisation de la photo du joueur
            lj.ajouteJoueur(js); // ajout du joueur a la liste des joueurs selectionnées
        }
        if(Amadeus.isSelected()){
            Joueur ja=new Joueur("Amadeus", "communs"); // Création d'un nouveau joueur Amdeus  de la familles des communs
            ja.setPhoto(new ImageIcon(getClass().getResource("/img/joueurDefaut.png"))); // initialisation de la photo du joueur
            lj.ajouteJoueur(ja); // ajout du joueur a la liste des joueurs selectionnées
        }*/
        
        this.ok = true;  //  initialiser l'attribut ok par true
        this.setVisible(false); // rend la boite de dialogue invisible 
        }
        else {
            Edition.setText("Vous devez choisissez la taille du jeu et deux joueurs au minimum");
        }
        
            
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;  //  initialiser l'attribut ok par false
        this.setVisible(false);// rend la boite de dialogue invisible 
            
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Amadeus;
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JCheckBox Jack;
    private javax.swing.JCheckBox JeanSebastien;
    private javax.swing.JCheckBox Lara;
    private javax.swing.JButton Valider;
    private javax.swing.JRadioButton avance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton debutant;
    private javax.swing.JRadioButton enfant;
    private javax.swing.JRadioButton expert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
