
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */

/**
 *
 * @author admin
 */
public class SaisieJoueurDlg extends java.awt.Dialog {
    private Joueur jr;
    private boolean ok;
    private ImageIcon photo;
    private LesPersonnages lp;
    
     public Joueur getjr() {
        return this.jr;
    }

    public boolean getOk() {
        return this.ok;
    }

    public ImageIcon getPhoto() {
        return this.photo;
    }
    public LesPersonnages getLp(){
        return lp;
    }
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal,LesPersonnages lesp) {
        super(parent, modal);
        initComponents();
         this.lp = lesp;
        this.jr = null;
        this.photo = null;
        this.ok = false;
        initListeFamilles();
    }
     public void initListeFamilles(){
        ArrayList lst = this.lp.getFamilles();
        DefaultListModel mod = new DefaultListModel();
        ListeFamille.setModel(mod);
        for(int i=0;i<lst.size();i++)
            mod.addElement(lst.get(i));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeFamille = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BParcourir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BValider = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel4.setText("Créez votre Joueur !");
        jPanel2.add(jLabel4);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Donnez votre pseudo !");
        jPanel7.add(jLabel1, java.awt.BorderLayout.NORTH);
        jPanel7.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Quelle est votre familles préférée de personnages ?");
        jPanel8.add(jLabel2, java.awt.BorderLayout.NORTH);

        ListeFamille.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(ListeFamille);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Choisissez une photo !");
        jPanel9.add(jLabel3, java.awt.BorderLayout.NORTH);

        BParcourir.setText("Parcourir");
        BParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParcourirActionPerformed(evt);
            }
        });
        jPanel9.add(BParcourir, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout());

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanel5.add(BAnnuler);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        jPanel5.add(BValider);

        jPanel4.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel6.setLayout(new java.awt.GridLayout());
        jPanel6.add(Photo);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void BParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParcourirActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jf= new JFileChooser();
            if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
            {
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            photo = new ImageIcon(img);
            Photo.setIcon(photo);
        }
 
    }//GEN-LAST:event_BParcourirActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
         int ind = ListeFamille.getSelectedIndex();
        Joueur jp;
        if(jTextField1.getText() != null && ind != -1){
            jp = new Joueur(jTextField1.getText(),lp.getPerso(ind).getFamille());
            if(this.photo != null)  {                    
                jp.setPhoto(photo);
            }
                this.ok = true;
                this.setVisible(false);
                this.jr=jp;
        }   
        else if(jTextField1.getText().equals(""))
            jTextField1.setText("pseudo vide");
        this.ok=true;
        this.setVisible(false);
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;
        this.setVisible(false);
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BValider;
    private javax.swing.JList<String> ListeFamille;
    private javax.swing.JButton Photo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
