
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ak859784
 */
public class VisuJoueursDlg extends java.awt.Dialog {
        private LesJoueurs lj;
    /**
     * Creates new form VisuJoueursDlg
     */
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal,LesJoueurs l) {
        super(parent, modal); // appel au cnst de la sous-classe 
        initComponents(); // appel a la methode initComponents qui contruit l'intérface qui a était faite
        this.lj=l;  // initialiser l'attribut de la classe a partir de LesJoueurs passé en paramètre
        initTrombi(); // appel a la méthode initTrombi
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Affiche = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Panneau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Choisissez un joueur pour voir ses caractéristiques");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout());

        Affiche.setText("Afficher");
        Affiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficheActionPerformed(evt);
            }
        });
        jPanel3.add(Affiche);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(Panneau, java.awt.BorderLayout.CENTER);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false); // rend la boite de dialogue invisible
        dispose(); // récuperer l'espace mémoire
    }//GEN-LAST:event_closeDialog

    private void AfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficheActionPerformed
        // TODO add your handling code here:
        int nb=this.lj.getNbJoueurs(); // initialiser nb par le nombre des joueures de l'attribut 
        for(int i=0;i<nb;i++){  // une boucle qui se rèpete nb fois 
            JButton jb=(JButton)Panneau.getComponent(i); // recuperation de l'i-ème bouton
            Joueur j = lj.getJoueur(i); // recuperation de l'i-ème joueur 
            
           // JButton jb = new JButton();
            jb.setIcon(j.getImage()); //  Modifier l'icon du Button(jb) par image du joueur 
       
        }
    }//GEN-LAST:event_AfficheActionPerformed
        private void initTrombi()
        { int nb = this.lj.getNbJoueurs(); //initialiser nb par le nombre de joueurs selectionner
        Panneau.setLayout(new GridLayout(1, nb));//donner au Panneau un GridLayout
        for (int i=0; i< nb; i++)  //une boucle qui se répéte nb fois
        {
        JButton jb= new JButton(); //creation d'un nouveau bouton
        Joueur j= lj.getJoueur(i); //recuperé le i-émé joueur
        jb.setName(""+i); //changer le nom du bouton par l'indice de la boucle
        jb.addActionListener(new java.awt.event.ActionListener() { //lier le bouton avec un ecouteur pour qu'il soit cliquable
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        AfficheInfosJoueur(evt); //appel à la methode AfficheInfoJoueur
        }
        });
        Panneau.add(jb); //ajouter le bouton dans le Panneau
        }
        this.pack(); } // pour ajuster correctement la taille des composants après les ajouts si besoin
        
        private void AfficheInfosJoueur(java.awt.event.ActionEvent evt) {
            JButton j = (JButton) evt.getSource(); // recuperation de la bouton cliquée
            int i = Integer.parseInt(j.getName()); // convertir le nom du bouton a un entier 
            Edition.setText(""+lj.getJoueur(i)); // affichage des informations du joueur dans la zone d'édition 
        }
    /**
     * @param args the command line arguments
     */
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Affiche;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
